/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    ArticleDialog: typeof import('./src/components/ArticleDialog.vue')['default']
    ArticleQR: typeof import('./src/components/ArticleQR.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    CategoryPill: typeof import('./src/components/CategoryPill.vue')['default']
    CodeField: typeof import('./src/components/CodeField.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    IssueDialog: typeof import('./src/components/IssueDialog.vue')['default']
    LibraryCard: typeof import('./src/components/LibraryCard.vue')['default']
    MemberDialog: typeof import('./src/components/MemberDialog.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanButton: typeof import('./src/components/ScanButton.vue')['default']
    ScanDialog: typeof import('./src/components/ScanDialog.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
  }
}
